packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/organs/*'
  - 'cli'
allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@vxnus/e-knowledge@0.1.2'
  - '@vxnus/e@0.1.3'
