packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/organs/*'
  - 'cli'
allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@vxnus/e-knowledge@0.1.4'
  - '@vxnus/e@0.1.4'
  - '@astrojs/markdown-satteri@0.4.1'
  - astro@7.3.2
